# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8d9f272dfe9241ee951f58f1167f0a9e0bb2b593941524c71c2ef56b9c3914b46b4be49209ba7cd6ec12f348c110ed22c78d0e875d9274c0b04140a1db54626

test:
  secret_key_base: 1d3815b01bfe3e45c8bf8f22f87f8d453fe5863af982f1ed6062e90e88485718aa5e1c5de4113bbad637f1ce54f3617dd721d3ca411b72d0c3dbda8e39c42a0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
